### ISSUE TITLE
github/sanritzの権限をいただけませんか？

### ISSUE THREAD

**Issue by daisatojp** [kagerouttepaso/PassZipper#3]
@kagerouttepaso 
橘内さん
お久しぶりです。
サンリツオートメイションの佐藤大です。
リポジトリと無関係のissue作ってすみません。
↓の管理者権限ほしいのですが、良いですか？
https://github.com/sanritz
宜しくお願い致します。

**Comment by kagerouttepaso** [comment]
いいよー
代わりにTPIP-Comunityの管理者権限も引き取ってくれ。

**Comment by daisatojp** [comment]
どうもです。

> TPIP-Comunityの管理者権限

TPIPユーザーコミュニティ( http://www.tpip-dev.org/ )のことですか？

**Comment by daisatojp** [comment]
メール気づかなかったです。
↓のことですね。
https://github.com/TPIP-Community
承知しました。
